name: NestJS Backend

on:
  pull_requests:
    branches: 
      - main

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: 12
      - run: npm ci
      - run: npm run test
      - run: npm run build
