name: NestJS Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node_version: 12
      - run: npm ci
      - run: npm run test
      - run: npm run build
      


